export default {
  refName: {
    type: 'text',
    value: 'ref',
    description:
      "Overlay component access `ref` to directly mutate styles when calculation position to prevent re-renders. It's being used for both `trigger`, and `children` element at the same time. Your components must accept refs with the same naming.",
    group: 'Overlay',
  },
  triggerRefName: {
    type: 'text',
    description: 'A key name how a `ref` should be passed to trigger component',
    group: 'Overlay',
  },
  contentRefName: {
    type: 'text',
    description: 'A key name how a `ref` should be passed to content component',
    group: 'Overlay',
  },
  isOpen: {
    type: 'boolean',
    value: false,
    description: '',
    group: 'Overlay',
  },
  openOn: {
    type: 'select',
    options: ['click', 'hover'],
    value: 'click',
    description: '',
    group: 'Overlay',
  },
  closeOn: {
    type: 'select',
    options: ['click', 'triggerClick', 'hover', 'manual'],
    value: 'click',
    description: '',
    group: 'Overlay',
  },
  type: {
    type: 'select',
    options: ['dropdown', 'tooltip', 'popover', 'modal'],
    value: 'dropdown',
    description: '',
    group: 'Overlay',
  },
  align: {
    type: 'select',
    options: ['top', 'left', 'bottom', 'right'],
    value: 'bottom',
    description: '',
    group: 'Overlay',
  },
  alignX: {
    type: 'select',
    options: ['left', 'center', 'right'],
    value: 'left',
    description: '',
    group: 'Overlay',
  },
  alignY: {
    type: 'select',
    options: ['top', 'center', 'bottom'],
    value: 'bottom',
    description: '',
    group: 'Overlay',
  },
  position: {
    type: 'select',
    options: ['fixed', 'absolute', 'relative', 'static'],
    value: 'fixed',
    description: '',
    group: 'Overlay',
  },
  offsetX: {
    type: 'number',
    value: 0,
    description: '',
    group: 'Overlay',
  },
  offsetY: {
    type: 'number',
    value: 0,
    description: '',
    group: 'Overlay',
  },
  throttleDelay: {
    type: 'number',
    value: 200,
    description: '',
    group: 'Overlay',
  },
  children: {
    description: 'A content to be rendered when Overlay is open',
  },
} as const
